### PR TITLE
style: `"` for comment

### LINKED ISSUE #37: [FR] `\s` after `"` when commenting
Currently, `\t` is inserted after `"` when using `editor.action.commentLine`, please use `\s` instead of `\t`, that would be a space saver ;).

### PR DESCRIPTION
**Pull request by wenfangdu**
closes #37

### CODE REVIEW

**Comment by wenfangdu** [comment]
@XadillaX Bro, what's blocking this?

**Comment by XadillaX** [comment]
> @XadillaX Bro, what's blocking this?

I saw your change is `"\""` but not `"\"\s"`?

**Comment by wenfangdu** [comment]
@XadillaX Currently it's two spaces when commenting, this PR reduces it to one space, e.g. `"  foo` => `" foo`.

Sorry if #37 created any confusion.

**Comment by XadillaX** [comment]
published in v2.2.0

**Comment by XadillaX** [comment]
@all-contributors add @wenfangdu  to code.

**Pull request merged**
